### ISSUE TITLE
Submit to Gentoo proxy maintainers

### ISSUE THREAD

**Issue by ghost** [christgau/wsdd-gentoo#2]
Hi!

Would you consider submitting your ebuild to Gentoo Proxy maintainers? This way they take care of the inclusions in the Portage tree. Unless of course you want to be an official Gentoo maintainer :) 

https://wiki.gentoo.org/wiki/Project:Proxy_Maintainers

>Proxy Maintainers facilitates high quality user contributions and works to enhance user-developer cooperation in maintaining packages.

**Comment by christgau** [comment]
> Would you consider submitting your ebuild to Gentoo Proxy maintainers? 

Why not!?  😃

I'm in preparation of a new "release" for [wsdd](https://www.github.com/christgau/wsdd) which basically means tagging (one of) the latest commit. 😉 Since there are new features like a man page and support for Gentoo's conf.d (see christgau/wsdd#13) a new ebuild will be provided as well in the near future. I'll contact the proxy maintainers as soon my time allows.

**Comment by ghost** [comment]
Wonderful :)

**Comment by ghost** [comment]
A little update on Gentoo wiki ;-)

https://wiki.gentoo.org/wiki/Samba/Guide#Installing_the_Web_Service_Discovery_host_daemon

**Comment by christgau** [comment]
I submitted a new package of the current version (0.5) to the [GURU project](https://wiki.gentoo.org/wiki/Project:GURU), which can be considered as an incubator for new packages or what [AUR](https://aur.archlinux.org/) is for Arch. Nevertheless, I'm leaving the PR in proxy-maint https://github.com/gentoo/gentoo/pull/12393 open.

**Comment by christgau** [comment]
Proxy is more or less dead: https://github.com/gentoo/gentoo/pull/12393#issuecomment-864582571

I'll continue providing this overlay and pushing into the Guru overlay as well. Nevertheless, I close this issue as the proxy maint overlay has apparently no future.
